- name: Install MicroK8s using snap
  command: snap install microk8s --classic --channel={{ microk8s_version }}

- name: Check MicroK8s status
  command: microk8s status --wait-ready

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Checking if the group exists
  group:
    name: "{{ ansible_user_group_name }}"
    state: present

- name: Add Ansible user to microk8s group
  user:
    name: "{{ ansible_user_name }}"
    groups: microk8s
    append: true

- name: Change ownership to Ansible user (and group)
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group_name }}"

- name: Add kubectl and helm aliases
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    create: yes
  with_items: "{{ bash_aliases }}"

- name: Enable add-ons
  command: microk8s enable dns storage rbac

- name: Instal Metallb
  command: microk8s enable metallb:{{ metallb_ip_range }}
