# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provision "file", source: "./k8s", destination: "/home/vagrant/k8s"
  # config.vm.provision "file", source: "./kong", destination: "/home/vagrant/kong"
  config.vm.provision "file", source: "./flask-app-chart", destination: "/home/vagrant/flask-app-chart"
  config.vm.provision "file", source: "./ansible", destination: "/home/vagrant/ansible"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "6144"
    vb.cpus = "2"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yaml"
    # ansible.verbose = "v"
    ansible.inventory_path = "ansible/inventory/hosts.yaml"
    ansible.limit = "localhost"
  end
end
