apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "flask-app-chart.fullname" . }}
  name: flask-app
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000
  selector:
    app: flask-app
