apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-{{ .Values.ReleaseName }}
spec:
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}
