FROM python:3.7.4 as builder

WORKDIR /opt/app

COPY requirements.txt .  
RUN pip install --no-cache-dir -r requirements.txt        



FROM python:3.7.4 

COPY --from=builder /usr/local/lib/python3.7/site-packages/ /usr/local/lib/python3.7/site-packages/       
COPY ./api.py . 

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "--log-level", "debug", "api:app"]