- hosts: localhost
  vars:
    - ansible_user_name: vagrant
    - ansible_user_group_name: vagrant
    - microk8s_version: 1.27
    - bash_aliases:
      - { alias: "kubectl", command: "microk8s kubectl" }
      - { alias: 'helm', command: 'microk8s helm' }
    - metallb_ip_range: 192.168.56.12-192.168.56.20


  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: true

    - name: Upgrade all packages
      apt:
        upgrade: safe
      become: true

    - name: Install prerequisites for MicroK8s
      apt:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - curl
        - iptables
        - snapd

    - name: Create and Configure a MicroK8s cluster
      block: 
        - name: Install MicroK8s using snap
          command: snap install microk8s --classic --channel={{microk8s_version}}
        
        - name: Check MicroK8s status
          command: microk8s status --wait-ready

        - name: Create .kube directory
          file:
            path: "{{ ansible_env.HOME }}/.kube"
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Checking if the group exists
          group: 
            name: "{{ ansible_user_group_name }}"
            state: present 

        - name: Add Ansible user to microk8s group
          user:
            name: "{{ ansible_user_name }}"
            groups: microk8s
            append: true
        
        - name: Change ownership to Ansible user (and group)
          file:
            path: "{{ ansible_env.HOME }}/.kube"
            state: directory
            owner: "{{ ansible_user_name }}"
            group: "{{ ansible_user_group_name }}"
      
        - name: Add kubectl and helm aliases
          lineinfile:
            dest: "{{ ansible_env.HOME }}/.bash_aliases"
            line: 'alias {{ item.alias }}="{{ item.command }}"'
            create: yes
          with_items: "{{ bash_aliases }}"        
        
        - name: Enable add-ons
          command: microk8s enable dns storage rbac 
          
        - name: Instal Metallb
          command: microk8s enable metallb:{{ metallb_ip_range }}
      become: true
  
    - name: Install Kong Ingress Controller (KIC)
      block:
        - name: Install Kubernetes Gateway API 
          command: microk8s.kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml

        - name: Install Kubernetes Gateway CRD
          command: microk8s.kubectl apply -f /home/vagrant/kong/gateway-api-crd.yaml
            
        - name: Add Kong helm repo
          command: microk8s.helm repo add kong https://charts.konghq.com
        
        - name: Update Helm repo
          command: microk8s.helm repo update

        - name: Check if the Kong namespace exists
          command: microk8s.kubectl get namespace kong
          ignore_errors: true
          register: namespace_kong_output

        - name: Install KIC Helm
          command: microk8s.helm install kong kong/ingress -n kong --create-namespace
          when: namespace_kong_output.rc != 0

      become: true

    - name: Install Argo CD 
      block: 
        - name: Create namespace argocd
          command: microk8s.kubectl create namespace argocd

        - name: Deploy Argo CD into MicroK8s
          command: microk8s.kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      become: true

         

            
