- name: Creates a directory for the Gateway CRD configuration file
  file:
    path: /home/vagrant/kong
    state: directory

- name: Copy the Gateway CRD configuration file
  copy:
    src: gateway-api-crd.yaml
    dest: /home/vagrant/kong/gateway-api-crd.yaml

- name: Install Kubernetes Gateway API
  command: microk8s.kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml

- name: Install Kubernetes Gateway CRD
  command: microk8s.kubectl apply -f /home/vagrant/kong/gateway-api-crd.yaml

- name: Add Kong helm repo
  command: microk8s.helm repo add kong https://charts.konghq.com

- name: Update Helm repo
  command: microk8s.helm repo update

- name: Check if the Kong namespace exists
  command: microk8s.kubectl get namespace kong
  ignore_errors: true
  register: namespace_kong_output

- name: Install KIC Helm
  command: microk8s.helm install kong kong/ingress -n kong --create-namespace
  when: namespace_kong_output.rc != 0
